CREATE TABLE "Users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "display_name" varchar NOT NULL,
  "email" varchar NOT NULL,
  "password_hash" varchar,
  "third_party_data" varchar,
  "third_party_provider" varchar,
  "phone_no" varchar
);

CREATE TABLE "User_PFP" (
  "id" int PRIMARY KEY,
  "data" bytea
);

CREATE TABLE "Items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" int NOT NULL,
  "creator_id" int NOT NULL,
  "shared_to" int NOT NULL,
  "title" varchar,
  "notes" text,
  "reminder" bool
);

CREATE TABLE "Shared_To" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "shared_to_text" varchar
);

CREATE TABLE "Item_type" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar NOT NULL
);

CREATE TABLE "Calendar_Details" (
  "id" int PRIMARY KEY,
  "date_from" timestamp,
  "date_to" timestamp,
  "place" varchar,
  "shared_to" int
);

CREATE TABLE "Attending" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "calendar_id" int NOT NULL,
  "person" int NOT NULL
);

CREATE TABLE "Todo_Items" (
  "id" INT PRIMARY KEY,
  "item_id" int NOT NULL,
  "item_text" varchar,
  "item_done" bool
  
);

CREATE TABLE "Friends" (
  "user_first_id" int,
  "user_second_id" int,
  "status" int,
  PRIMARY KEY(user_first_id,user_second_id)
);

CREATE TABLE "friends_status" (
  "id" int PRIMARY KEY,
  "status" varchar
);

ALTER TABLE "Items" ADD FOREIGN KEY ("type") REFERENCES "Item_type" ("id");

ALTER TABLE "Users" ADD FOREIGN KEY ("id") REFERENCES "User_PFP" ("id");

ALTER TABLE "Items" ADD FOREIGN KEY ("creator_id") REFERENCES "Users" ("id");

ALTER TABLE "Attending" ADD FOREIGN KEY ("calendar_id") REFERENCES "Calendar_Details" ("id");

ALTER TABLE "Items" ADD FOREIGN KEY ("id") REFERENCES "Calendar_Details" ("id");

ALTER TABLE "Calendar_Details" ADD FOREIGN KEY ("shared_to") REFERENCES "Shared_To" ("id");

ALTER TABLE "Todo_Items" ADD FOREIGN KEY ("item_id") REFERENCES "Items" ("id");

ALTER TABLE "Friends" ADD FOREIGN KEY ("user_first_id") REFERENCES "Users" ("id");
ALTER TABLE "Friends" ADD FOREIGN KEY ("user_second_id") REFERENCES "Users" ("id");
ALTER TABLE "Friends" ADD FOREIGN KEY ("status") REFERENCES "friends_status" ("id");